### ISSUE TITLE
Reserveren van datum en tijd

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#52]
- [ ] Datum en tijd kan worden gekozen
- [ ] Datum en tijd worden vastgelegd 
- [ ] bijbehorend tijdsblok wordt geblokkeerd voor andere reserveringen
