### ISSUE TITLE
Toevoegen van gegevens overledene en belanghebbende aan de reservering (uit BRP)

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#55]
- [ ] Gegevens van overleden kunnen worden toegevoegd aan het verzoek
- [ ] Gegevens van belanghebbende kunnen worden toegevoegd aan het verzoek
- [ ] De gegevens worden overgenomen uit de BRP
