### ISSUE TITLE
Opties kiezen bij een begrafenis

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#57]
- [ ] De mogelijke hulpmiddelen en ceremoniële handelingen van de gekozen begraafplaats kunnen naar keuze worden toegevoegd aan het verzoek.
- [ ] De middelen zijn opgenomen in de planning
- [ ] De middelen zijn gereserveerd voor deze begrafenis
