### ISSUE TITLE
Beschikbare Component voor opstellen en berekenen orders

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#58]
- [ ] component voor opstellen orders is geïnstalleerd
- [ ] component voor opstellen orders is getest en werkt volledig
- [ ] orderregels voor de begrafenis en alle opties kunne worden vastgelegd
- [ ] kosten van elke orderregel kan worden berekend
- [ ] totale kosten van de order kunnen worden berekend
- [ ] klant kan de order accepteren
