### ISSUE TITLE
Direct berekenen van de kosten van de gekozen begrafenis en bevestigen van de opdracht

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#59]
- [ ] Bij elke keuze die gemaakt wordt, worden direct de kosten weergegeven
- [ ] bij het maken van keuzen worden orderregels vastgelegd
- [ ] bij het definitief maken van de reservering, kan de order worden opgemaakt
- [ ] de order kan door de begrafenisondernemer worden bevestigd
