### ISSUE TITLE
invulen verzoek organiseren begrafenis en versturen bericht naar beheerder

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#74]
- [ ] alle benodigde gegevens kunnen worden ingevuld in de planner
- [ ] het verzoek wordt goed verwerkt
- [ ] alle informatie is terugvindbaar is het dashboard van de begraafplaatsbeheerder
