### ISSUE TITLE
een stabiele demo-omgeving en beheerst deploymentproces

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#76]
We willen ongestoord demo's kunnen geven en erop kunnen vertrouwen dat er geen onverwachte fouten en verstoringen optreden. 

We streven naar een goede afstemming tussen de processen voor ontwikkeling, deployment en beheer en goede processen die de kwaliteit van de onderdelen borgen DevOps kan hiervoor een oplossing zijn..

Borging Demo omgeving:
- [ ] Hoe borgen we de deployment en werking
- [ ] Welke afspraken moeten we daarvoor maken
- [ ] Welke contractvorm
- [ ] DevOps aanpak, hoe richten we dat in?

**Comment by PatrickCastenmiller** [comment]
Dit hebben we redelijk goed in de hand. We kunnen geode demo's geven. Voldoet.
